### ISSUE TITLE
Can't compile assets: ES6 syntax error

### ISSUE THREAD

**Issue by manno** [voc/voctoweb#332]
We can't deploy anymore:

```
ubuntu@media:/vagrant$ RACK_ENV=production rails assets:precompile
I, [2018-10-03T12:54:46.088184 #3048]  INFO -- : Writing /vagrant/public/assets/embed-d8402f8bd4ff35a95fde03727c761eca5c46e3e08e12647e312501feed6cf174.css
I, [2018-10-03T12:54:46.090756 #3048]  INFO -- : Writing /vagrant/public/assets/embed-d8402f8bd4ff35a95fde03727c761eca5c46e3e08e12647e312501feed6cf174.css.gz
rails aborted!
Uglifier::Error: Unexpected token: name (vtt_url). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
/var/lib/gems/2.3.0/gems/uglifier-4.1.14/lib/uglifier.rb:234:in `parse_result'
/var/lib/gems/2.3.0/gems/uglifier-4.1.14/lib/uglifier.rb:216:in `run_uglifyjs'
/var/lib/gems/2.3.0/gems/uglifier-4.1.14/lib/uglifier.rb:168:in `compile'
```

**Comment by manno** [comment]
fixed by https://github.com/voc/voctoweb/commit/76325339c16621dd95ed96aeedaaa7cc61eb8545

**Comment by blinry** [comment]
Thanks for the fix! :) I guess ES6 support is a good thing!

**Comment by chmich** [comment]
Thanks!
